# Configuration for mockery
# This setup assumes mocks will be placed in a "mocks" subfolder relative to each package.

disable-version-string: True
with-expecter: true

# Structuring options
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"

issue-845-fix: True
resolve-type-alias: False

packages:
  github.com/bioform/go-web-app-template/pkg/action:
    config:
      all: True
    interfaces:
      IfaceWithCustomBuildTagInComment:
