services:

# SMTP Server
  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: docker-workspace-smtp
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - docker_workspace_network
networks:
  docker_workspace_network:
    driver: bridge
