database:
  dsn: <set it via DATABASE_DSN environment variable>

event:
  topic: events

kafka:
  bootstrap:
    servers: localhost:9092

email:
  smtp:
    host: localhost
    port: 1025
    username: your_username
    password: your_password
    from: no-reply@go-webapp-template.com
    tls: true
