// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	action "github.com/bioform/go-web-app-template/pkg/action"

	mock "github.com/stretchr/testify/mock"
)

// AfterCommitCallback is an autogenerated mock type for the AfterCommitCallback type
type AfterCommitCallback struct {
	mock.Mock
}

type AfterCommitCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *AfterCommitCallback) EXPECT() *AfterCommitCallback_Expecter {
	return &AfterCommitCallback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *AfterCommitCallback) Execute(_a0 context.Context, _a1 action.Action) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, action.Action) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AfterCommitCallback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AfterCommitCallback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 action.Action
func (_e *AfterCommitCallback_Expecter) Execute(_a0 interface{}, _a1 interface{}) *AfterCommitCallback_Execute_Call {
	return &AfterCommitCallback_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *AfterCommitCallback_Execute_Call) Run(run func(_a0 context.Context, _a1 action.Action)) *AfterCommitCallback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(action.Action))
	})
	return _c
}

func (_c *AfterCommitCallback_Execute_Call) Return(_a0 error) *AfterCommitCallback_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AfterCommitCallback_Execute_Call) RunAndReturn(run func(context.Context, action.Action) error) *AfterCommitCallback_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewAfterCommitCallback creates a new instance of AfterCommitCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAfterCommitCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *AfterCommitCallback {
	mock := &AfterCommitCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
